services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data

  mongo-express:
    image: mongo-express
    container_name: ws-server
    restart: always
    ports:
      - 8081:8081
volumes:
  mongo: {}
